CREATE DATABASE IF NOT EXISTS cart;

USE cart;

CREATE TABLE IF NOT EXISTS cart (
    id VARCHAR(100) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    quantity INT NOT NULL
);

