version: '3.8'
services:

  planner:
    build: 
      context: ./PlannerComplex
      dockerfile: planner.Dockerfile
    ports:
      - "5001:80"

  generative_ai:
    build: 
      context: ./PlannerComplex
      dockerfile: generative_ai.Dockerfile
    ports:
      - "5002:80"

  currency_service:
    build: 
      context: ./PlannerComplex
      dockerfile: currency_service.Dockerfile
    ports:
      - "5003:80"

  weather:
    build: 
      context: ./PlannerComplex
      dockerfile: weather.Dockerfile
    ports:
      - "5004:80"
