version: '3.8'

volumes:
  rabbitmq_data:
  my_volume:


services:


  generative_ai:
    build: 
      context: ./PlannerComplex/
      dockerfile: generative_ai.Dockerfile
    image: choxa1/ai:1.0
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"

  currency_service:
    build: 
      context: ./PlannerComplex/
      dockerfile: currency_service.Dockerfile
    image: choxa1/currency:1.0
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5003:5003"

  weather:
    build: 
      context: ./PlannerComplex/
      dockerfile: weather.Dockerfile
    image: choxa1/weather:1.0
    restart: always
    environment:
      PYTHONUNBUFFERED: 1    
    ports:
      - "5004:5004"


  planner:
    build: 
      context: ./PlannerComplex/
      dockerfile: planner.Dockerfile
    image: choxa1/planner:1.0
    restart: always
    depends_on:
      - generative_ai
      - currency_service
      - weather
      - rabbitmq
      - firebase
      - notification
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      gemini_URL: http://generative_ai:5002/plan
      weather_URL: http://weather:5004/weather
      currency_URL: http://currency_service:5003/exchange
      email_URL: http://firebase:5010/email
      PYTHONUNBUFFERED: 1      
    ports:
      - "5001:5001"

  firebase:
    build:
      context: ./LoginService/
      dockerfile: firebase.Dockerfile
    image: choxa1/firebase:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/user_data
      PYTHONUNBUFFERED: 1
    ports:
      - "5010:5010"


  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json
      - rabbitmq_data:/var/lib/rabbitmq

  notification:
    build:
      context: ./ShoppingComplex/
      dockerfile: notification.Dockerfile
    image: choxa1/notification:1.0
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      notification_queue_name: Notification
      PYTHONUNBUFFERED: 1
      
  payment_handler:
    build:
      context: ./ShoppingComplex/
      dockerfile: payment_handler.Dockerfile
    image: choxa1/payment_handler:1.0
    restart: always
    depends_on:
      - rabbitmq
      - payment
      - notification
      - shoppingcart
    environment:
      shopping_cart_url: http://shoppingcart:5006/cart
      payment_url: http://payment:5007/create-checkout-session
      notification_url: http://notification:5008/notification
      recipient_url: http://payment:5007/get_emails
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/cart
      rabbit_host: rabbitmq
      rabbit_port: 5672 
      PYTHONUNBUFFERED: 1
    ports:
      - "5909:5909"

  payment:
    build:
      context: ./ShoppingComplex/
      dockerfile: payment.Dockerfile
    image: choxa1/payment:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/cart
      PYTHONUNBUFFERED: 1
    ports:
      - "5007:5007"

  shopItems:
    build:
      context: ./ShoppingComplex/
      dockerfile: shopItems.Dockerfile
    image: choxa1/shopitems:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/item
      PYTHONUNBUFFERED: 1
    ports:
      - "5005:5005"


  shoppingcart:
    build:
      context: ./ShoppingComplex/
      dockerfile: shoppingcart.Dockerfile
    image: choxa1/shoppingcart:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/cart
      PYTHONUNBUFFERED: 1
    ports:
      - "5006:5006"

  detection:
    build:
      context: ./TranslationComplex/
      dockerfile: detection.Dockerfile
    image: choxa1/detection:1.0
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5011:5011"
    volumes:
      - my_volume:/data
  
  error:
    build:
      context: ./TranslationComplex/
      dockerfile: error.Dockerfile
    image: choxa1/error:1.0
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5014:5014"
  
  orchestrator:
    build:
      context: ./TranslationComplex/
      dockerfile: orchestrator.Dockerfile
    image: choxa1/orchestrator:1.0
    restart: always
    depends_on:
      - detection
      - error
      - text_replacement
      - translation
    environment:
      detect_url: http://detection:5011/detect_text
      translate_url: http://translation:5012/get_languages
      decipher_url: http://translation:5012/translate_text
      replacement_url: http://text_replacement:5013/replace_text
      error_url: http://error:5014/log_error
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"
    volumes:
      - my_volume:/data

  text_replacement:
    build:
      context: ./TranslationComplex/
      dockerfile: text_replacement.Dockerfile
    image: choxa1/text_replacement:1.0
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5013:5013"
    volumes:
      - my_volume:/data
  
  translation:
    build:
      context: ./TranslationComplex/
      dockerfile: translation.Dockerfile
    image: choxa1/translation:1.0
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5012:5012"
    volumes:
      - my_volume:/data
