version: '3.8'

volumes:
  rabbitmq_data:


services:


  generative_ai:
    build: 
      context: ./PlannerComplex/
      dockerfile: generative_ai.Dockerfile
    image: choxa1/ai:1.0
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"

  currency_service:
    build: 
      context: ./PlannerComplex/
      dockerfile: currency_service.Dockerfile
    image: choxa1/currency:1.0
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5003:5003"

  weather:
    build: 
      context: ./PlannerComplex/
      dockerfile: weather.Dockerfile
    image: choxa1/weather:1.0
    restart: always
    environment:
      PYTHONUNBUFFERED: 1    
    ports:
      - "5004:5004"


  planner:
    build: 
      context: ./PlannerComplex/
      dockerfile: planner.Dockerfile
    image: choxa1/planner:1.0
    restart: always
    depends_on:
      - generative_ai
      - currency_service
      - weather
    environment:
      PYTHONUNBUFFERED: 1      
    ports:
      - "5001:5001"

  # firebase:
  #   build:
  #     context: ./LoginService/
  #     dockerfile: firebase.Dockerfile
  #   image: choxa1/firebase:1.0
  #   restart: always
  #   environment:
  #     PYTHONUNBUFFERED: 1
  #   ports:
  #     - "5010:5010"

  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json
      - rabbitmq_data:/var/lib/rabbitmq

  notification:
    build:
      context: ./ShoppingComplex/
      dockerfile: notification.Dockerfile
    image: choxa1/notification:1.0
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      notification_queue_name: Notification
      PYTHONUNBUFFERED: 1
      
  payment_handler:
    build:
      context: ./ShoppingComplex/
      dockerfile: payment_handler.Dockerfile
    image: choxa1/payment_handler:1.0
    restart: always
    depends_on:
      - rabbitmq
      - payment
      - notification
      - shoppingcart
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672 
      PYTHONUNBUFFERED: 1
    ports:
      - "5909:5909"    

  payment:
    build:
      context: ./ShoppingComplex/
      dockerfile: payment.Dockerfile
    image: choxa1/payment:1.0
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5007:5007"

  shopItems:
    build:
      context: ./ShoppingComplex/
      dockerfile: shopItems.Dockerfile
    image: choxa1/shopitems:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/item
      PYTHONUNBUFFERED: 1
    ports:
      - "5005:5005"


  shoppingcart:
    build:
      context: ./ShoppingComplex/
      dockerfile: shoppingcart.Dockerfile
    image: choxa1/shoppingcart:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/cart
      PYTHONUNBUFFERED: 1
    ports:
      - "5006:5006"

