version: '3.8'
services:


  generative_ai:
    build: 
      context: ./PlannerComplex/
      dockerfile: generative_ai.Dockerfile
    image: choxa1/ai:1.0
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"

  currency_service:
    build: 
      context: ./PlannerComplex/
      dockerfile: currency_service.Dockerfile
    image: choxa1/currency:1.0
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5003:5003"

  weather:
    build: 
      context: ./PlannerComplex/
      dockerfile: weather.Dockerfile
    image: choxa1/weather:1.0
    restart: always
    environment:
      PYTHONUNBUFFERED: 1    
    ports:
      - "5004:5004"


  planner:
    build: 
      context: ./PlannerComplex/
      dockerfile: planner.Dockerfile
    image: choxa1/planner:1.0
    restart: always
    depends_on:
      - generative_ai
      - currency_service
      - weather
    environment:
      PYTHONUNBUFFERED: 1      
    ports:
      - "5001:5001"
